document.writeln("<div class=\'lightbox js-lightbox\' data-comp=\'Lightbox\' aria-hidden=\'true\' role=\'dialog\' aria-labelledby=\'sr-lightbox-title\' data-comp-id=\'comp_7\'>");
document.writeln("        <header class=\'lightbox__header\'>");
document.writeln("          <div class=\'lightbox__header-title\'>");
document.writeln("            <span class=\'lightbox__button js-lightbox-close\' data-comp=\'Tooltip\' data-props-tooltip=\'{&quot;tip&quot;: &quot;Close&quot;, &quot;direction&quot;: &quot;bottom&quot;}\' data-comp-id=\'comp_8\'>");
document.writeln("              <i class=\'material-icons material-icons--padded mdc-ripple-surface mdc-ripple-upgraded--unbounded mdc-ripple-upgraded\' data-mdc-ripple-is-unbounded=\'\' tabindex=\'0\' style=\'--mdc-ripple-fg-size:24px; --mdc-ripple-fg-scale:1.66667; --mdc-ripple-left:8px; --mdc-ripple-top:8px;\'>close</i>");
document.writeln("              <div class=\'tooltip js-tooltip-bottom\' style=\'left: 44px; margin-left: -23px; top: 65.5px;\'>Close</div>");
document.writeln("              <div class=\'tooltip js-tooltip-bottom\'>Close</div>");
document.writeln("              <div class=\'tooltip js-tooltip-bottom\'>Close</div></span>");
document.writeln("            <h2 class=\'lightbox__title js-lightbox-title\'></h2>");
document.writeln("          </div>");
document.writeln("          <div class=\'lightbox__actions\'>");
document.writeln("            <button type=\'button\' name=\'button\' class=\'lightbox-redlines-toggle js-redline-sidebar-toggle\' data-comp=\'Tooltip\' data-props-tooltip=\'{&quot;tip&quot;: &quot;View Specs&quot;, &quot;direction&quot;: &quot;bottom&quot;}\' data-comp-id=\'comp_9\'>");
document.writeln("              <i class=\'material-icons material-icons--padded mdc-ripple-surface mdc-ripple-upgraded--unbounded mdc-ripple-upgraded\' data-mdc-ripple-is-unbounded=\'\' style=\'--mdc-ripple-fg-size:0px; --mdc-ripple-fg-scale:NaN; --mdc-ripple-left:0px; --mdc-ripple-top:0px;\'>flip</i>");
document.writeln("              <div class=\'tooltip js-tooltip-bottom\'>View Specs</div>");
document.writeln("              <div class=\'tooltip js-tooltip-bottom\'>View Specs</div>");
document.writeln("              <div class=\'tooltip js-tooltip-bottom\'>View Specs</div></button>");
document.writeln("            <button type=\'button\' name=\'button\' class=\'lightbox__button js-share\' data-comp=\'Tooltip\' data-props-tooltip=\'{&quot;tip&quot;: &quot;Share&quot;, &quot;direction&quot;: &quot;bottom&quot;}\' data-comp-id=\'comp_10\'>");
document.writeln("              <i class=\'material-icons material-icons--padded mdc-ripple-surface mdc-ripple-upgraded--unbounded mdc-ripple-upgraded\' data-mdc-ripple-is-unbounded=\'\' style=\'--mdc-ripple-fg-size:24px; --mdc-ripple-fg-scale:1.66667; --mdc-ripple-left:8px; --mdc-ripple-top:8px;\'>share</i>");
document.writeln("              <div class=\'tooltip js-tooltip-bottom\'>Share</div>");
document.writeln("              <div class=\'tooltip js-tooltip-bottom\'>Share</div>");
document.writeln("              <div class=\'tooltip js-tooltip-bottom\'>Share</div></button>");
document.writeln("          </div>");
document.writeln("        </header>");
document.writeln("        <div class=\'lightbox__template js-zoom-wrapper\'>");
document.writeln("          <div class=\'lightbox__content js-lightbox-content\'>");
document.writeln("            <img class=\'ui-loader\' src=\'./src/loader.svg\' alt=\'loader\' aria-hidden=\'true\'></div>");
document.writeln("          <div class=\'redline-sidebar js-lightbox-sidebar-container\' data-comp=\'RedlineSidebar\' data-comp-id=\'comp_11\'>");
document.writeln("            <div class=\'redline-sidebar__button-wrapper\' data-comp=\'Tooltip\' data-props-tooltip=\'{&quot;tip&quot;: &quot;Image only&quot;, &quot;direction&quot;: &quot;left&quot;}\' data-comp-id=\'comp_12\'>");
document.writeln("              <button type=\'button\' class=\'redline-sidebar__item mdc-ripple-surface js-image js-redline-sidebar-item mdc-ripple-upgraded\' value=\'image\' style=\'--mdc-ripple-fg-size:0px; --mdc-ripple-fg-scale:Infinity;\'>");
document.writeln("                <span class=\'redline-sidebar__label-text\'>Image only</span></button>");
document.writeln("              <div class=\'tooltip js-tooltip-left\'>Image only</div>");
document.writeln("              <div class=\'tooltip js-tooltip-left\'>Image only</div>");
document.writeln("              <div class=\'tooltip js-tooltip-left\'>Image only</div></div>");
document.writeln("            <div class=\'redline-sidebar__button-wrapper\' data-comp=\'Tooltip\' data-props-tooltip=\'{&quot;tip&quot;: &quot;Measurements&quot;, &quot;direction&quot;: &quot;left&quot;}\' data-comp-id=\'comp_13\'>");
document.writeln("              <button type=\'button\' class=\'redline-sidebar__item mdc-ripple-surface js-measurements js-redline-sidebar-item mdc-ripple-upgraded\' value=\'measurements\' style=\'--mdc-ripple-fg-size:0px; --mdc-ripple-fg-scale:Infinity;\'>");
document.writeln("                <i class=\'material-icons\'>format_shapes</i>");
document.writeln("                <span class=\'redline-sidebar__label-text\'>Measurements</span></button>");
document.writeln("              <div class=\'tooltip js-tooltip-left\'>Measurements</div>");
document.writeln("              <div class=\'tooltip js-tooltip-left\'>Measurements</div>");
document.writeln("              <div class=\'tooltip js-tooltip-left\'>Measurements</div></div>");
document.writeln("            <div class=\'redline-sidebar__button-wrapper\' data-comp=\'Tooltip\' data-props-tooltip=\'{&quot;tip&quot;: &quot;Text&quot;, &quot;direction&quot;: &quot;left&quot;}\' data-comp-id=\'comp_14\'>");
document.writeln("              <button type=\'button\' class=\'redline-sidebar__item mdc-ripple-surface js-text js-redline-sidebar-item mdc-ripple-upgraded\' value=\'text\' style=\'--mdc-ripple-fg-size:0px; --mdc-ripple-fg-scale:Infinity;\'>");
document.writeln("                <i class=\'material-icons\'>format_size</i>");
document.writeln("                <span class=\'redline-sidebar__label-text\'>Text</span></button>");
document.writeln("              <div class=\'tooltip js-tooltip-left\'>Text</div>");
document.writeln("              <div class=\'tooltip js-tooltip-left\'>Text</div>");
document.writeln("              <div class=\'tooltip js-tooltip-left\'>Text</div></div>");
document.writeln("            <div class=\'redline-sidebar__button-wrapper\' data-comp=\'Tooltip\' data-props-tooltip=\'{&quot;tip&quot;: &quot;Color&quot;, &quot;direction&quot;: &quot;left&quot;}\' data-comp-id=\'comp_15\'>");
document.writeln("              <button type=\'button\' class=\'redline-sidebar__item mdc-ripple-surface js-colors js-redline-sidebar-item mdc-ripple-upgraded\' value=\'colors\' style=\'--mdc-ripple-fg-size:0px; --mdc-ripple-fg-scale:Infinity;\'>");
document.writeln("                <i class=\'material-icons\'>palette</i>");
document.writeln("                <span class=\'redline-sidebar__label-text\'>Color</span></button>");
document.writeln("              <div class=\'tooltip js-tooltip-left\'>Color</div>");
document.writeln("              <div class=\'tooltip js-tooltip-left\'>Color</div>");
document.writeln("              <div class=\'tooltip js-tooltip-left\'>Color</div></div>");
document.writeln("            <div class=\'redline-sidebar__button-wrapper\' data-comp=\'Tooltip\' data-props-tooltip=\'{&quot;tip&quot;: &quot;Shape and Elevation&quot;, &quot;direction&quot;: &quot;left&quot;}\' data-comp-id=\'comp_16\'>");
document.writeln("              <button type=\'button\' class=\'redline-sidebar__item mdc-ripple-surface js-shapes js-redline-sidebar-item mdc-ripple-upgraded\' value=\'shapes\' style=\'--mdc-ripple-fg-size:0px; --mdc-ripple-fg-scale:Infinity;\'>");
document.writeln("                <i class=\'material-icons\'>rounded_corner</i>");
document.writeln("                <span class=\'redline-sidebar__label-text\'>Shape and Elevation</span></button>");
document.writeln("              <div class=\'tooltip js-tooltip-left\'>Shape and Elevation</div>");
document.writeln("              <div class=\'tooltip js-tooltip-left\'>Shape and Elevation</div>");
document.writeln("              <div class=\'tooltip js-tooltip-left\'>Shape and Elevation</div></div>");
document.writeln("            <div class=\'redline-sidebar__button-wrapper\' data-comp=\'Tooltip\' data-props-tooltip=\'{&quot;tip&quot;: &quot;Components&quot;, &quot;direction&quot;: &quot;left&quot;}\' data-comp-id=\'comp_17\'>");
document.writeln("              <button type=\'button\' class=\'redline-sidebar__item mdc-ripple-surface js-components js-redline-sidebar-item mdc-ripple-upgraded\' value=\'components\' style=\'--mdc-ripple-fg-size:0px; --mdc-ripple-fg-scale:Infinity;\'>");
document.writeln("                <i class=\'material-icons\'>category</i>");
document.writeln("                <span class=\'redline-sidebar__label-text\'>Components</span></button>");
document.writeln("              <div class=\'tooltip js-tooltip-left\'>Components</div>");
document.writeln("              <div class=\'tooltip js-tooltip-left\'>Components</div>");
document.writeln("              <div class=\'tooltip js-tooltip-left\'>Components</div></div>");
document.writeln("            <div class=\'redline-sidebar__button-wrapper\' data-comp=\'Tooltip\' data-props-tooltip=\'{&quot;tip&quot;: &quot;Notes&quot;, &quot;direction&quot;: &quot;left&quot;}\' data-comp-id=\'comp_18\'>");
document.writeln("              <button type=\'button\' class=\'redline-sidebar__item mdc-ripple-surface js-notes js-redline-sidebar-item mdc-ripple-upgraded\' value=\'notes\' style=\'--mdc-ripple-fg-size:0px; --mdc-ripple-fg-scale:Infinity;\'>");
document.writeln("                <i class=\'material-icons\'>notes</i>");
document.writeln("                <span class=\'redline-sidebar__label-text\'>Notes</span></button>");
document.writeln("              <div class=\'tooltip js-tooltip-left\'>Notes</div>");
document.writeln("              <div class=\'tooltip js-tooltip-left\'>Notes</div>");
document.writeln("              <div class=\'tooltip js-tooltip-left\'>Notes</div></div>");
document.writeln("            <div class=\'redline-sidebar__toggles js-redline-layer-toggles\'>");
document.writeln("              <div class=\'mdc-checkbox redline-sidebar__toggle redline-sidebar__toggle--dimensions\'>");
document.writeln("                <input type=\'checkbox\' id=\'dimensions\' class=\'mdc-checkbox__native-control js-redline-layer-toggle\'>");
document.writeln("                <div class=\'mdc-checkbox__background\'>");
document.writeln("                  <svg class=\'mdc-checkbox__checkmark\' viewBox=\'0 0 24 24\'>");
document.writeln("                    <path class=\'mdc-checkbox__checkmark-path\' fill=\'none\' stroke=\'white\' d=\'M1.73,12.91 8.1,19.28 22.79,4.59\'></path>");
document.writeln("                  </svg>");
document.writeln("                  <div class=\'mdc-checkbox__mixedmark\'></div>");
document.writeln("                </div>");
document.writeln("              </div>");
document.writeln("              <label for=\'dimensions\'>Dimensions</label>");
document.writeln("              <div class=\'mdc-checkbox redline-sidebar__toggle redline-sidebar__toggle--padding\'>");
document.writeln("                <input type=\'checkbox\' id=\'padding\' class=\'mdc-checkbox__native-control js-redline-layer-toggle\'>");
document.writeln("                <div class=\'mdc-checkbox__background\'>");
document.writeln("                  <svg class=\'mdc-checkbox__checkmark\' viewBox=\'0 0 24 24\'>");
document.writeln("                    <path class=\'mdc-checkbox__checkmark-path\' fill=\'none\' stroke=\'white\' d=\'M1.73,12.91 8.1,19.28 22.79,4.59\'></path>");
document.writeln("                  </svg>");
document.writeln("                  <div class=\'mdc-checkbox__mixedmark\'></div>");
document.writeln("                </div>");
document.writeln("              </div>");
document.writeln("              <label for=\'padding\'>Padding</label>");
document.writeln("              <div class=\'mdc-checkbox redline-sidebar__toggle redline-sidebar__toggle--typography\'>");
document.writeln("                <input type=\'checkbox\' id=\'typography\' class=\'mdc-checkbox__native-control js-redline-layer-toggle\'>");
document.writeln("                <div class=\'mdc-checkbox__background\'>");
document.writeln("                  <svg class=\'mdc-checkbox__checkmark\' viewBox=\'0 0 24 24\'>");
document.writeln("                    <path class=\'mdc-checkbox__checkmark-path\' fill=\'none\' stroke=\'white\' d=\'M1.73,12.91 8.1,19.28 22.79,4.59\'></path>");
document.writeln("                  </svg>");
document.writeln("                  <div class=\'mdc-checkbox__mixedmark\'></div>");
document.writeln("                </div>");
document.writeln("              </div>");
document.writeln("              <label for=\'typography\'>Text baseline</label></div>");
document.writeln("          </div>");
document.writeln("          <nav class=\'carousel__nav\'>");
document.writeln("            <button class=\'carousel__button carousel__button--prev mdc-ripple-surface js-carousel-prev mdc-ripple-upgraded\' data-comp=\'Tooltip\' data-props-tooltip=\'{&quot;tip&quot;: &quot;Previous&quot;, &quot;direction&quot;: &quot;right&quot;}\' style=\'--mdc-ripple-fg-size:0px; --mdc-ripple-fg-scale:Infinity;\' data-comp-id=\'comp_19\'>");
document.writeln("              <i class=\'material-icons\'>chevron_left</i>");
document.writeln("              <div class=\'tooltip js-tooltip-right\'>Previous</div>");
document.writeln("              <div class=\'tooltip js-tooltip-right\'>Previous</div>");
document.writeln("              <div class=\'tooltip js-tooltip-right\'>Previous</div></button>");
document.writeln("            <button class=\'carousel__button carousel__button--next mdc-ripple-surface js-carousel-next mdc-ripple-upgraded\' data-comp=\'Tooltip\' data-props-tooltip=\'{&quot;tip&quot;: &quot;Next&quot;, &quot;direction&quot;: &quot;left&quot;}\' style=\'--mdc-ripple-fg-size:0px; --mdc-ripple-fg-scale:Infinity;\' data-comp-id=\'comp_20\'>");
document.writeln("              <i class=\'material-icons\'>chevron_right</i>");
document.writeln("              <div class=\'tooltip js-tooltip-left\'>Next</div>");
document.writeln("              <div class=\'tooltip js-tooltip-left\'>Next</div>");
document.writeln("              <div class=\'tooltip js-tooltip-left\'>Next</div></button>");
document.writeln("          </nav>");
document.writeln("          <div class=\'zoom-buttons\' data-comp=\'Zoom\' data-comp-id=\'comp_21\'>");
document.writeln("            <div class=\'zoom-buttons__wrapper\'>");
document.writeln("              <button class=\'mdc-button-zoom js-zoom-out\' data-comp=\'Tooltip\' data-props-tooltip=\'{&quot;tip&quot;: &quot;Zoom out&quot;, &quot;direction&quot;: &quot;top&quot;}\' data-comp-id=\'comp_22\'>");
document.writeln("                <i class=\'material-icons mdc-ripple-surface mdc-ripple-upgraded\' style=\'--mdc-ripple-fg-size:28.8px; --mdc-ripple-fg-scale:2.60817; --mdc-ripple-fg-translate-start:3.99063px, 21.2367px; --mdc-ripple-fg-translate-end:7.6px, 9.6px;\'>remove</i>");
document.writeln("                <div class=\'tooltip js-tooltip-top\' style=\'left: 66px; margin-left: -34px; top: 706px;\'>Zoom out</div>");
document.writeln("                <div class=\'tooltip js-tooltip-top\'>Zoom out</div>");
document.writeln("                <div class=\'tooltip js-tooltip-top\'>Zoom out</div></button>");
document.writeln("              <button class=\'mdc-button-zoom js-zoom-reset inactive\' data-comp=\'Tooltip\' data-props-tooltip=\'{&quot;tip&quot;: &quot;Reset&quot;, &quot;direction&quot;: &quot;top&quot;}\' data-comp-id=\'comp_23\'>");
document.writeln("                <i class=\'material-icons mdc-ripple-surface mdc-ripple-upgraded\' style=\'--mdc-ripple-fg-size:28.8px; --mdc-ripple-fg-scale:2.60817;\'>search</i>");
document.writeln("                <div class=\'tooltip js-tooltip-top\' style=\'left: 110px; margin-left: -23px; top: 706px;\'>Reset</div>");
document.writeln("                <div class=\'tooltip js-tooltip-top\'>Reset</div>");
document.writeln("                <div class=\'tooltip js-tooltip-top\'>Reset</div></button>");
document.writeln("              <button class=\'mdc-button-zoom js-zoom-in\' data-comp=\'Tooltip\' data-props-tooltip=\'{&quot;tip&quot;: &quot;Zoom in&quot;, &quot;direction&quot;: &quot;top&quot;}\' data-comp-id=\'comp_24\'>");
document.writeln("                <i class=\'material-icons mdc-ripple-surface mdc-ripple-upgraded\' style=\'--mdc-ripple-fg-size:28.8px; --mdc-ripple-fg-scale:2.60817; --mdc-ripple-fg-translate-start:17.557px, 3.90078px; --mdc-ripple-fg-translate-end:7.6px, 9.6px;\'>add</i>");
document.writeln("                <div class=\'tooltip js-tooltip-top\' style=\'left: 154px; margin-left: -30px; top: 706px;\'>Zoom in</div>");
document.writeln("                <div class=\'tooltip js-tooltip-top\'>Zoom in</div>");
document.writeln("                <div class=\'tooltip js-tooltip-top\'>Zoom in</div></button>");
document.writeln("              <div class=\'zoom-buttons__extras\'>");
document.writeln("                <button class=\'mdc-button-zoom js-colorpicker-toggle\' data-comp=\'Tooltip Colorpicker\' data-props-tooltip=\'{&quot;tip&quot;: &quot;Color picker&quot;, &quot;direction&quot;: &quot;top&quot;}\' data-comp-id=\'comp_25 comp_26\'>");
document.writeln("                  <i class=\'material-icons mdc-ripple-surface mdc-ripple-upgraded\' style=\'--mdc-ripple-fg-size:0px; --mdc-ripple-fg-scale:Infinity;\'>colorize</i>");
document.writeln("                  <div class=\'tooltip js-tooltip-top\'>Color picker</div>");
document.writeln("                  <div class=\'tooltip js-tooltip-top\'>Color picker</div>");
document.writeln("                  <div class=\'tooltip js-tooltip-top\'>Color picker</div></button>");
document.writeln("                <button class=\'mdc-button-zoom js-ruler-toggle\' data-comp=\'Tooltip Ruler\' data-props-tooltip=\'{&quot;tip&quot;: &quot;Ruler&quot;, &quot;direction&quot;: &quot;top&quot;}\' data-comp-id=\'comp_27 comp_28\'>");
document.writeln("                  <i class=\'material-icons mdc-ripple-surface mdc-ripple-upgraded\' style=\'--mdc-ripple-fg-size:0px; --mdc-ripple-fg-scale:Infinity;\'>straighten</i>");
document.writeln("                  <div class=\'tooltip js-tooltip-top\'>Ruler</div>");
document.writeln("                  <div class=\'tooltip js-tooltip-top\'>Ruler</div>");
document.writeln("                  <div class=\'tooltip js-tooltip-top\'>Ruler</div></button>");
document.writeln("              </div>");
document.writeln("            </div>");
document.writeln("          </div>");
document.writeln("        </div>");
document.writeln("        <aside class=\'mdc-dialog\' role=\'alertdialog\' aria-labelledby=\'mdc-dialog-label\' aria-describedby=\'mdc-dialog-description\' data-comp=\'Share\' data-comp-id=\'comp_29\'>");
document.writeln("          <div class=\'mdc-dialog__surface\'>");
document.writeln("            <header class=\'mdc-dialog__header\'>");
document.writeln("              <h2 id=\'mdc-dialog-label\' class=\'mdc-dialog__header__title\'>Share</h2>");
document.writeln("              <button type=\'button\' class=\'mdc-dialog-share-close js-dialog-close\'>");
document.writeln("                <i class=\'material-icons material-icons--padded mdc-ripple-surface mdc-ripple-upgraded--unbounded mdc-ripple-upgraded\' data-mdc-ripple-is-unbounded=\'\' style=\'--mdc-ripple-fg-size:19.2px; --mdc-ripple-fg-scale:1.66667; --mdc-ripple-left:6px; --mdc-ripple-top:6px;\'>close</i></button>");
document.writeln("            </header>");
document.writeln("            <section id=\'mdc-dialog-description\' class=\'mdc-dialog__body\'>");
document.writeln("              <input type=\'text\' readonly=\'\' class=\'mdc-dialog-share-url js-share-url\'>");
document.writeln("              <button type=\'button\' class=\'mdc-button mdc-ripple-surface mdc-dialog-copy js-dialog-copy mdc-ripple-upgraded\' style=\'--mdc-ripple-fg-size:30.72px; --mdc-ripple-fg-scale:2.23777;\'>Copy</button></section>");
document.writeln("          </div>");
document.writeln("          <div class=\'mdc-dialog__backdrop\'></div>");
document.writeln("        </aside>");
document.writeln("      </div>");
document.writeln("      <div class=\'mdc-snackbar snackbar-wrapper\' data-comp=\'Snackbar\' aria-live=\'assertive\' aria-atomic=\'true\' aria-hidden=\'true\' data-comp-id=\'comp_30\'>");
document.writeln("        <div class=\'mdc-snackbar__text\'></div>");
document.writeln("        <div class=\'mdc-snackbar__action-wrapper\'>");
document.writeln("          <button type=\'button\' class=\'mdc-button mdc-snackbar__action-button\' aria-hidden=\'true\'></button>");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("");